2025-03-26 10:08:52,807 INFO    MainThread:173742 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-26 10:08:52,807 INFO    MainThread:173742 [wandb_setup.py:_flush():67] Configure stats pid to 173742
2025-03-26 10:08:52,807 INFO    MainThread:173742 [wandb_setup.py:_flush():67] Loading settings from /home/alexhuge/.config/wandb/settings
2025-03-26 10:08:52,807 INFO    MainThread:173742 [wandb_setup.py:_flush():67] Loading settings from /home/alexhuge/Documents/GitHub/RoboMan/roboman_train/humanoid/scripts/wandb/settings
2025-03-26 10:08:52,807 INFO    MainThread:173742 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-26 10:08:52,807 INFO    MainThread:173742 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/alexhuge/Documents/GitHub/RoboMan/roboman_train/humanoid/scripts/wandb/run-20250326_100852-n5xvrimv/logs/debug.log
2025-03-26 10:08:52,807 INFO    MainThread:173742 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/alexhuge/Documents/GitHub/RoboMan/roboman_train/humanoid/scripts/wandb/run-20250326_100852-n5xvrimv/logs/debug-internal.log
2025-03-26 10:08:52,811 INFO    MainThread:173742 [wandb_init.py:init():761] calling init triggers
2025-03-26 10:08:52,812 INFO    MainThread:173742 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'algorithm': {'clip_param': 0.2, 'desired_kl': 0.01, 'entropy_coef': 0.001, 'gamma': 0.994, 'lam': 0.9, 'learning_rate': 1e-05, 'max_grad_norm': 1.0, 'num_learning_epochs': 2, 'num_mini_batches': 4, 'schedule': 'adaptive', 'use_clipped_value_loss': True, 'value_loss_coef': 1.0}, 'init_member_classes': {}, 'policy': {'actor_hidden_dims': [512, 256, 128], 'critic_hidden_dims': [768, 256, 128], 'init_noise_std': 1.0}, 'runner': {'algorithm_class_name': 'PPO', 'checkpoint': -1, 'experiment_name': 'wsybot_ppo', 'load_run': -1, 'max_iterations': 10001, 'num_steps_per_env': 60, 'policy_class_name': 'ActorCritic', 'resume': False, 'resume_path': None, 'run_name': '', 'save_interval': 100}, 'runner_class_name': 'OnPolicyRunner', 'seed': 3407, 'asset': {'angular_damping': 0.0, 'armature': 0.0, 'collapse_fixed_joints': True, 'default_dof_drive_mode': 3, 'density': 0.001, 'disable_gravity': False, 'file': '{LEGGED_GYM_ROOT_DIR}/resources/robots/wsybot/urdf/wsybot.urdf', 'fix_base_link': False, 'flip_visual_attachments': False, 'foot_name': 'ankle_roll', 'knee_name': 'knee', 'linear_damping': 0.0, 'max_angular_velocity': 1000.0, 'max_linear_velocity': 1000.0, 'name': 'wsybot', 'penalize_contacts_on': ['base_link', 'left_knee_link', 'right_knee_link'], 'replace_cylinder_with_capsule': False, 'self_collisions': 0, 'terminate_after_contacts_on': ['base_link', 'left_knee_link', 'right_knee_link'], 'thickness': 0.01}, 'commands': {'curriculum': False, 'heading_command': True, 'max_curriculum': 1.0, 'num_commands': 4, 'ranges': {'ang_vel_yaw': [-0.3, 0.3], 'heading': [-3.14, 3.14], 'lin_vel_x': [-0.3, 0.6], 'lin_vel_y': [-0.3, 0.3]}, 'resampling_time': 8.0}, 'control': {'action_scale': 0.3, 'damping': {'leg_roll': 2.0, 'leg_pitch': 2.0, 'leg_yaw': 2.0, 'knee': 2.0, 'ankle': 2.0}, 'decimation': 20, 'stiffness': {'leg_roll': 150.0, 'leg_pitch': 75.0, 'leg_yaw': 150.0, 'knee': 75.0, 'ankle': 75.0}}, 'domain_rand': {'action_delay': 0.5, 'action_noise': 0.02, 'added_mass_range': [-0.5, 0.5], 'friction_range': [0.1, 2.0], 'max_push_ang_vel': 0.4, 'max_push_vel_xy': 0.2, 'push_interval': 200.0, 'push_interval_s': 4, 'push_robots': True, 'randomize_base_mass': True, 'randomize_friction': True}, 'env': {'c_frame_stack': 3, 'env_spacing': 3.0, 'episode_length_s': 24, 'frame_stack': 15, 'num_actions': 12, 'num_envs': 16384, 'num_observations': 705, 'num_privileged_obs': 219, 'num_single_obs': 47, 'send_timeouts': True, 'single_num_privileged_obs': 73, 'use_ref_actions': False}, 'init_state': {'ang_vel': [0.0, 0.0, 0.0], 'default_joint_angles': {'left_leg_roll_joint': 0.0, 'left_leg_yaw_joint': 0.0, 'left_leg_pitch_joint': 0.0, 'left_knee_joint': 0.0, 'left_ankle_pitch_joint': 0.0, 'left_ankle_roll_joint': 0.0, 'right_leg_roll_joint': 0.0, 'right_leg_yaw_joint': 0.0, 'right_leg_pitch_joint': 0.0, 'right_knee_joint': 0.0, 'right_ankle_pitch_joint': 0.0, 'right_ankle_roll_joint': 0.0}, 'lin_vel': [0.0, 0.0, 0.0], 'pos': [0.0, 0.0, 0.765], 'rot': [0.0, 0.0, 0.0, 1.0]}, 'noise': {'add_noise': True, 'noise_level': 0.6, 'noise_scales': {'ang_vel': 0.1, 'dof_pos': 0.05, 'dof_vel': 0.5, 'height_measurements': 0.1, 'lin_vel': 0.05, 'quat': 0.03}}, 'normalization': {'clip_actions': 18.0, 'clip_observations': 18.0, 'obs_scales': {'ang_vel': 1.0, 'dof_pos': 1.0, 'dof_vel': 0.05, 'height_measurements': 5.0, 'lin_vel': 2.0, 'quat': 1.0}}, 'rewards': {'base_height_target': 0.765, 'cycle_time': 0.7, 'max_contact_force': 700, 'max_dist': 0.5, 'min_dist': 0.2, 'only_positive_rewards': True, 'scales': {'action_smoothness': -0.5, 'base_acc': 0.2, 'base_height': 0.2, 'collision': -1.0, 'default_joint_pos': 1.5, 'dof_acc': -1e-07, 'dof_vel': -0.0005, 'feet_air_time': 3, 'feet_clearance': 3.5, 'feet_contact_forces': -0.01, 'feet_contact_number': 1.2, 'feet_distance': 0.2, 'foot_slip': -0.08, 'joint_pos': 1.6, 'knee_distance': 0.2, 'low_speed': 0.2, 'orientation': 2.5, 'torques': -1e-05, 'track_vel_hard': 0.5, 'tracking_ang_vel': 1.1, 'tracking_lin_vel': 1.2, 'vel_mismatch_exp': 0.5}, 'target_feet_height': 0.25, 'target_joint_pos_scale': 0.17, 'tracking_sigma': 5}, 'safety': {'pos_limit': 1.0, 'torque_limit': 0.85, 'vel_limit': 1.0}, 'sim': {'dt': 0.001, 'gravity': [0.0, 0.0, -9.81], 'physx': {'bounce_threshold_velocity': 0.1, 'contact_collection': 2, 'contact_offset': 0.01, 'default_buffer_size_multiplier': 5, 'max_depenetration_velocity': 1.0, 'max_gpu_contact_pairs': 8388608, 'num_position_iterations': 4, 'num_threads': 10, 'num_velocity_iterations': 1, 'rest_offset': 0.0, 'solver_type': 1}, 'substeps': 1, 'up_axis': 1}, 'terrain': {'border_size': 25, 'curriculum': False, 'dynamic_friction': 0.6, 'horizontal_scale': 0.1, 'max_init_terrain_level': 10, 'measure_heights': False, 'measured_points_x': [-0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8], 'measured_points_y': [-0.5, -0.4, -0.3, -0.2, -0.1, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5], 'mesh_type': 'plane', 'num_cols': 20, 'num_rows': 20, 'restitution': 0.0, 'selected': False, 'slope_treshold': 0.75, 'static_friction': 0.6, 'terrain_kwargs': None, 'terrain_length': 8.0, 'terrain_proportions': [0.2, 0.2, 0.4, 0.1, 0.1, 0, 0], 'terrain_width': 8.0, 'vertical_scale': 0.005}, 'viewer': {'lookat': [11.0, 5, 3.0], 'pos': [10, 0, 6], 'ref_env': 0}, '_wandb': {}}
2025-03-26 10:08:52,812 INFO    MainThread:173742 [wandb_init.py:init():784] starting backend
2025-03-26 10:08:52,812 INFO    MainThread:173742 [wandb_init.py:init():788] sending inform_init request
2025-03-26 10:08:52,832 INFO    MainThread:173742 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-26 10:08:52,832 INFO    MainThread:173742 [wandb_init.py:init():798] backend started and connected
2025-03-26 10:08:52,834 INFO    MainThread:173742 [wandb_init.py:init():891] updated telemetry
2025-03-26 10:08:52,901 INFO    MainThread:173742 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-26 10:08:53,703 INFO    MainThread:173742 [wandb_init.py:init():990] starting run threads in backend
2025-03-26 10:08:53,761 INFO    MainThread:173742 [wandb_run.py:_console_start():2375] atexit reg
2025-03-26 10:08:53,761 INFO    MainThread:173742 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-26 10:08:53,761 INFO    MainThread:173742 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-26 10:08:53,761 INFO    MainThread:173742 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-26 10:08:53,762 INFO    MainThread:173742 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-26 10:08:53,763 INFO    MainThread:173742 [wandb_run.py:_tensorboard_callback():1449] tensorboard callback: /home/alexhuge/Documents/GitHub/RoboMan/roboman_train/logs/wsybot_ppo/Mar26_10-08-50_, True
2025-03-26 10:10:51,774 INFO    MsgRouterThr:173742 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-26 10:10:54,780 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,783 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,785 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,786 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,786 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,787 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,789 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,790 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,790 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,791 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,792 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,792 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,793 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,793 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,794 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 10:10:54,794 ERROR   MainThread:173742 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/alexhuge/anaconda3/envs/roboman/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
